"use server";
import { revalidatePath } from "next/cache"; import { redirect } from "next/navigation";
import { requireOwner } from "@/lib/auth/owner"; import { deleteOwnerSession } from "@/lib/auth/session"; import { createAdminRedirect, deleteAdminRedirect, listAdminRedirects, updateAdminSettings, updatePageSeo } from "@/lib/admin/repository"; import { validateRedirectGraph } from "@/lib/content/redirects"; import { pageSeoInputSchema, redirectInputSchema, siteSettingsInputSchema } from "@/lib/content/validation"; import type { SeoRecord } from "@/lib/content/types";
import { normalizeAdSenseInput } from "@/lib/adsense/config";

export async function savePageSeo(pageKey: string, formData: FormData) { await requireOwner(); let seo: SeoRecord; try { seo = JSON.parse(String(formData.get("seoJson") ?? "{}")); } catch { redirect(`/admin/pages/${pageKey}?error=seo`); } const pathname = String(formData.get("pathname") ?? "/"); const introductionHtml = String(formData.get("introductionHtml") ?? ""); const parsed = pageSeoInputSchema.safeParse({ ...seo, pageKey, pathname, introductionHtml }); if (!parsed.success) redirect(`/admin/pages/${pageKey}?error=validation`); try { await updatePageSeo(pageKey, { browserTitle: seo.title, metaDescription: seo.description, introductionHtml, canonicalUrl: seo.canonical, breadcrumbLabel: seo.breadcrumbLabel, noIndex: seo.noIndex, noFollow: seo.noFollow, includeInSitemap: seo.includeInSitemap, sitemapPriority: String(seo.sitemapPriority), changeFrequency: seo.changeFrequency, openGraph: seo.openGraph, xCard: seo.xCard, keywords: [seo.targetKeyword, ...seo.supportingKeywords].filter(Boolean), schemaConfig: { type: seo.schemaType, properties: seo.schemaProperties }, faqItems: seo.faqItems }); } catch { redirect(`/admin/pages/${pageKey}?error=save`); } revalidatePath(pathname); revalidatePath("/sitemap.xml"); redirect(`/admin/pages/${pageKey}?saved=1`); }

export async function createRedirect(formData: FormData) { await requireOwner(); const input = { sourcePath: String(formData.get("sourcePath") ?? ""), destination: String(formData.get("destination") ?? ""), statusCode: Number(formData.get("statusCode")), enabled: formData.get("enabled") === "on" }; const parsed = redirectInputSchema.safeParse(input); if (!parsed.success) redirect("/admin/redirects?error=validation"); const existing = await listAdminRedirects(); try { validateRedirectGraph([...existing, { id: "new", ...input, statusCode: input.statusCode as 301 | 302 | 307 | 308, createdAt: "", updatedAt: "" }]); } catch { redirect("/admin/redirects?error=loop"); } try { await createAdminRedirect({ ...input, statusCode: input.statusCode as 301 | 302 | 307 | 308 }); } catch { redirect("/admin/redirects?error=save"); } revalidatePath(input.sourcePath); revalidatePath("/admin/redirects"); }
export async function deleteRedirect(id: string) { await requireOwner(); await deleteAdminRedirect(id); revalidatePath("/admin/redirects"); }

export async function saveSiteSettings(formData: FormData) { await requireOwner(); let adsense; try { adsense = normalizeAdSenseInput({ publisherId: String(formData.get("adsensePublisherId") ?? ""), code: String(formData.get("adsenseCode") ?? ""), enabled: formData.get("adsenseEnabled") === "on" }); } catch { redirect("/admin/settings?error=adsense"); } const input = { siteName: String(formData.get("siteName") ?? ""), titleTemplate: String(formData.get("titleTemplate") ?? ""), defaultDescription: String(formData.get("defaultDescription") ?? ""), socialProfiles: String(formData.get("socialProfiles") ?? "").split("\n").map((item) => item.trim()).filter(Boolean), verificationTokens: safeJson(formData.get("verificationTokens")), robotsRules: safeJson(formData.get("robotsRules")), googleAnalyticsMeasurementId: String(formData.get("googleAnalyticsMeasurementId") ?? "").trim().toUpperCase(), googleAnalyticsEnabled: formData.get("googleAnalyticsEnabled") === "on", adsensePublisherId: adsense.publisherId, adsenseCode: adsense.code, adsenseEnabled: adsense.enabled }; const parsed = siteSettingsInputSchema.safeParse(input); if (!parsed.success) redirect("/admin/settings?error=validation"); try { await updateAdminSettings(input); } catch { redirect("/admin/settings?error=save"); } revalidatePath("/", "layout"); redirect("/admin/settings?saved=1"); }
const safeJson = (value: FormDataEntryValue | null) => { try { return JSON.parse(String(value ?? "{}")); } catch { return {}; } };
export async function signOut() { await deleteOwnerSession(); redirect("/admin/login"); }
