"use server";
import { revalidatePath } from "next/cache"; import { redirect } from "next/navigation";
import { requireOwner } from "@/lib/auth/owner"; import { validateRedirectGraph } from "@/lib/content/redirects"; import { pageSeoInputSchema, redirectInputSchema, siteSettingsInputSchema } from "@/lib/content/validation"; import type { RedirectRecord, SeoRecord } from "@/lib/content/types"; import { createServerClient } from "@/lib/supabase/server";

export async function savePageSeo(pageKey: string, formData: FormData) { await requireOwner(); let seo: SeoRecord; try { seo = JSON.parse(String(formData.get("seoJson") ?? "{}")); } catch { redirect(`/admin/pages/${pageKey}?error=seo`); } const pathname = String(formData.get("pathname") ?? "/"); const introductionHtml = String(formData.get("introductionHtml") ?? ""); const parsed = pageSeoInputSchema.safeParse({ ...seo, pageKey, pathname, introductionHtml }); if (!parsed.success) redirect(`/admin/pages/${pageKey}?error=validation`); const supabase = await createServerClient(); const { error } = await supabase.from("page_seo").update({ browser_title: seo.title, meta_description: seo.description, introduction_html: introductionHtml, canonical_url: seo.canonical, breadcrumb_label: seo.breadcrumbLabel, no_index: seo.noIndex, no_follow: seo.noFollow, include_in_sitemap: seo.includeInSitemap, sitemap_priority: seo.sitemapPriority, change_frequency: seo.changeFrequency, open_graph: seo.openGraph, x_card: seo.xCard, keywords: [seo.targetKeyword, ...seo.supportingKeywords].filter(Boolean), schema_config: { type: seo.schemaType, properties: seo.schemaProperties }, faq_items: seo.faqItems }).eq("page_key", pageKey); if (error) redirect(`/admin/pages/${pageKey}?error=save`); revalidatePath(pathname); revalidatePath("/sitemap.xml"); redirect(`/admin/pages/${pageKey}?saved=1`); }

export async function createRedirect(formData: FormData) { await requireOwner(); const input = { sourcePath: String(formData.get("sourcePath") ?? ""), destination: String(formData.get("destination") ?? ""), statusCode: Number(formData.get("statusCode")), enabled: formData.get("enabled") === "on" }; const parsed = redirectInputSchema.safeParse(input); if (!parsed.success) redirect("/admin/redirects?error=validation"); const supabase = await createServerClient(); const { data } = await supabase.from("redirects").select("*"); const existing = (data ?? []).map(mapRedirect); try { validateRedirectGraph([...existing, { id: "new", ...input, statusCode: input.statusCode as 301 | 302 | 307 | 308, createdAt: "", updatedAt: "" }]); } catch { redirect("/admin/redirects?error=loop"); } const { data: created, error } = await supabase.from("redirects").insert({ source_path: input.sourcePath, destination: input.destination, status_code: input.statusCode, enabled: input.enabled }).select("id").single(); if (error) redirect("/admin/redirects?error=save"); await supabase.from("redirect_history").insert({ redirect_id: created.id, previous_value: { action: "created", ...input } }); revalidatePath(input.sourcePath); revalidatePath("/admin/redirects"); }
export async function deleteRedirect(id: string) { await requireOwner(); const supabase = await createServerClient(); const { data } = await supabase.from("redirects").select("*").eq("id", id).single(); if (data) await supabase.from("redirect_history").insert({ redirect_id: id, previous_value: { action: "deleted", ...data } }); await supabase.from("redirects").delete().eq("id", id); revalidatePath("/admin/redirects"); }
const mapRedirect = (row: Record<string, unknown>): RedirectRecord => ({ id: String(row.id), sourcePath: String(row.source_path), destination: String(row.destination), statusCode: Number(row.status_code) as 301 | 302 | 307 | 308, enabled: Boolean(row.enabled), createdAt: String(row.created_at), updatedAt: String(row.updated_at) });

export async function saveSiteSettings(formData: FormData) { await requireOwner(); const input = { siteName: String(formData.get("siteName") ?? ""), titleTemplate: String(formData.get("titleTemplate") ?? ""), defaultDescription: String(formData.get("defaultDescription") ?? ""), socialProfiles: String(formData.get("socialProfiles") ?? "").split("\n").map((item) => item.trim()).filter(Boolean), verificationTokens: safeJson(formData.get("verificationTokens")), robotsRules: safeJson(formData.get("robotsRules")) }; const parsed = siteSettingsInputSchema.safeParse(input); if (!parsed.success) redirect("/admin/settings?error=validation"); const supabase = await createServerClient(); const { error } = await supabase.from("site_settings").update({ site_name: input.siteName, title_template: input.titleTemplate, default_description: input.defaultDescription, social_profiles: input.socialProfiles, verification_tokens: input.verificationTokens, robots_rules: input.robotsRules }).eq("id", true); if (error) redirect("/admin/settings?error=save"); revalidatePath("/", "layout"); redirect("/admin/settings?saved=1"); }
const safeJson = (value: FormDataEntryValue | null) => { try { return JSON.parse(String(value ?? "{}")); } catch { return {}; } };
export async function signOut() { const supabase = await createServerClient(); await supabase.auth.signOut(); redirect("/admin/login"); }
